server.port: 8080
#data source
spring.datasource.url: jdbc:mysql://localhost:3306/cobumaDB
spring.datasource.username: appuser
spring.datasource.password: p2ssword
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.max-active: 100
spring.datasource.max-age: 600000
spring.datasource.max-idle: 20
spring.datasource.min-idle: 8
spring.datasource.initial-size: 10
#file upload
spring.http.multipart.max-file-size: 30MB
spring.http.multipart.maxFileSize: 30MB
spring.http.multipart.maxRequestSize: 30MB

# default to dev
spring.profiles.active: dev

---
spring.profiles: dev
#smtp
mail.username: awesomeqatesting@gmail.com
mail.password: testing@123
mail.host: smtp.gmail.com
mail.port: 587
server: localhost:8080